### ISSUE TITLE
Fixnum deprecated in Ruby 2.4

### ISSUE THREAD

**Issue by jakkn** [niv/nwn-lib#8]
Fixnum is used in [three places](https://github.com/niv/nwn-lib/search?utf8=%E2%9C%93&q=fixnum&type=) and is producing deprecated warnings. Especially visible when running `nwn-gff` on multiple files without silenced warnings.
```
/home/jakob/.gem/ruby/2.4.0/gems/nwn-lib-0.6.0/lib/nwn/gff/field.rb:172: warning: constant ::Fixnum is deprecated
/home/jakob/.gem/ruby/2.4.0/gems/nwn-lib-0.6.0/lib/nwn/gff/field.rb:172: warning: constant ::Fixnum is deprecated
/home/jakob/.gem/ruby/2.4.0/gems/nwn-lib-0.6.0/lib/nwn/gff/field.rb:172: warning: constant ::Fixnum is deprecated
```

**Comment by niv** [comment]
Thanks for the report. Seems it works fine otherwise in 2.4.

I've pushed a fix (duh) but it's not on the gem mirrors yet - need to roll a release with all the other commits/fixes that went in meanwhile.

**Comment by jakkn** [comment]
Gem updated to 0.6.1 with no difference in output and warnings gone.

Thanks niv, good stuff!
